import type { Metadata } from "next";
import { Luxurious_Roman, Quicksand } from "next/font/google";
import "./globals.css";
import Footer from "../components/layout/Footer";
import NavBar from "../components/layout/NavBar";
import { AuthProvider } from "../context/AuthContext";
import WishlistProvider from "../context/WishlistContext";
import { ShoppingBagProvider } from "../context/ShoppingBagContext";
import { Toaster } from "sonner";

export const luxuriousRoman = Luxurious_Roman({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-luxurious-roman",
});

export const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Let There Be Fragrance",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} ${luxuriousRoman.variable} antialiased`}
      >
        <AuthProvider>
          <WishlistProvider>
            <ShoppingBagProvider>
              <NavBar />
              <Toaster
                position="bottom-right"
                theme="system"
                toastOptions={{
                  style: {
                    borderRadius: "0px",
                    padding: "16px",
                    color: "white",
                  },
                }}
              />
              {children}
              <Footer />
            </ShoppingBagProvider>
          </WishlistProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
